In [2]:
import numpy as np
import torch

In [3]:
# Create a vector(Linear Algebra)
nv = np.array([[1, 2, 3, 4]])
print(nv)
print(" ")
# transpose it
print(nv.T)
print(nv)
nvT = nv.T
print(nvT)



[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [4]:
# Matrix
nM = np.array([[1, 2, 3, 4],
               [2, 3, 4, 5]])
print(nM)
nMT = nM.T
print(nMT)
print(nMT.T)

[[1 2 3 4]
 [2 3 4 5]]
[[1 2]
 [2 3]
 [3 4]
 [4 5]]
[[1 2 3 4]
 [2 3 4 5]]


In [5]:
tv = torch.tensor([ [1,2,3,4] ])
print(tv)
print(tv.T)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [6]:
nv1 = np.array([1, 2, 3, 4])
nv2 = np.array([0, 1, 0, -1])

# dot product
print(np.dot(nv1, nv2))
print(np.sum(nv1*nv2))

-2
-2


In [7]:
tv1 = torch.tensor([1, 2, 3, 4])
tv2 = torch.tensor([0, 1, 0, -1])

print(torch.dot(tv1, tv2))

tensor(-2)


In [8]:
# Matrix multiplication
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

print(np.round(A@B,2))
# print(np.round(A@C,2))
print(np.round(C.T@A,2))

[[-0.84 -2.98  0.71  2.03 -4.96]
 [ 0.54  2.89 -1.41  0.72  4.85]
 [ 0.82  0.24  1.81 -1.58  0.76]]
[[ 0.32  1.64  0.36  2.55]
 [-2.44 -1.49  2.57 -1.28]
 [-0.46 -0.87 -1.61 -1.99]
 [-0.55 -1.68 -2.2  -3.42]
 [-1.57 -1.96 -2.71 -4.14]
 [-1.27 -0.75 -0.89 -1.59]
 [-1.5  -1.92  2.86 -1.68]]


In [10]:
# Matrix multiplication
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor(C1,dtype=torch.float)

print(np.round(A@B,2))
print(np.round(A@C1,2))
print(np.round(A@C2,2))

tensor([[ 4.0600,  1.5800,  0.0600, -1.6400, -0.6300],
        [ 0.8600,  3.0000,  2.8600, -3.7100, -4.7000],
        [-3.2900, -1.2500, -0.3100, -0.4800, -1.8500]])
tensor([[ 1.4100,  0.9700, -6.9200, -2.4000,  2.2300, -1.2600, -3.0000],
        [ 1.9700,  1.3500, -8.1500, -2.8900,  3.1900, -1.9400, -0.0200],
        [ 0.0800, -1.6900,  0.4200,  0.7200,  3.3400,  0.0200,  0.1300]],
       dtype=torch.float64)
tensor([[ 1.4100,  0.9700, -6.9200, -2.4000,  2.2300, -1.2600, -3.0000],
        [ 1.9700,  1.3500, -8.1500, -2.8900,  3.1900, -1.9400, -0.0200],
        [ 0.0800, -1.6900,  0.4200,  0.7200,  3.3400,  0.0200,  0.1300]])
