In [ ]:
import numpy as np
import torch

In [7]:
# Create a vector(Linear Algebra)
nv = np.array([[1, 2, 3, 4]])
print(nv)
print(" ")
# transpose it
print(nv.T)
print(nv)
nvT = nv.T
print(nvT)



[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [11]:
# Matrix
nM = np.array([[1, 2, 3, 4],
               [2, 3, 4, 5]])
print(nM)
nMT = nM.T
print(nMT)
print(nMT.T)

[[1 2 3 4]
 [2 3 4 5]]
[[1 2]
 [2 3]
 [3 4]
 [4 5]]
[[1 2 3 4]
 [2 3 4 5]]


In [16]:
tv = torch.tensor([ [1,2,3,4] ])
print(tv)
print(tv.T)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [22]:
nv1 = np.array([1, 2, 3, 4])
nv2 = np.array([0, 1, 0, -1])

# dot product
print(np.dot(nv1, nv2))
print(np.sum(nv1*nv2))

-2
-2


In [23]:
tv1 = torch.tensor([1, 2, 3, 4])
tv2 = torch.tensor([0, 1, 0, -1])

print(torch.dot(tv1, tv2))

tensor(-2)


In [28]:
# Matrix multiplication
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

print(np.round(A@B,2))
# print(np.round(A@C,2))
print(np.round(C.T@A,2))

[[-1.29 -1.05  4.96 -3.88 -0.18]
 [ 1.02  0.69 -0.12  0.04  0.02]
 [ 1.21 -1.21 -0.54  0.72 -0.37]]
[[-0.22  0.23 -0.03  0.42]
 [-0.96  5.8  -3.28 -1.29]
 [-3.56  6.58 -2.45  3.11]
 [-0.39  2.47 -1.38  0.08]
 [-0.01  2.84 -1.86 -2.04]
 [ 0.94 -0.86  0.1  -0.61]
 [-0.97  0.58  0.15  2.45]]


In [32]:
# Matrix multiplication
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor(C1,dtype=torch.float)

print(np.round(A@B,2))
print(np.round(A@C1,2))
print(np.round(A@C2,2))

tensor([[ 0.6800, -1.4500, -2.7700, -0.0800,  0.4500],
        [ 0.2400,  1.7200, -1.1800, -1.6300, -1.2000],
        [-1.4100,  0.0100,  1.6700, -3.6300, -0.6200]])
tensor([[ 1.3300,  1.4800, -1.6000, -0.9800, -0.0800, -0.6700, -1.3000],
        [ 0.8600, -1.3900, -0.3800,  0.8100, -1.2500, -0.3600, -1.8500],
        [-2.5800,  0.6100,  3.7700,  2.2800,  1.3900,  0.4500, -1.7200]],
       dtype=torch.float64)
tensor([[ 1.3300,  1.4800, -1.6000, -0.9800, -0.0800, -0.6700, -1.3000],
        [ 0.8600, -1.3900, -0.3800,  0.8100, -1.2500, -0.3600, -1.8500],
        [-2.5800,  0.6100,  3.7700,  2.2800,  1.3900,  0.4500, -1.7200]])
