In [3]:
import numpy as np
# print(np.__version__)

a = np.array([1, 2, 3])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
#  byte size
print(a.itemsize)
print("-----------")
print(a[0])
a[0] = 10
print(a)

b = a * np.array([2, 0, 2])
print(b)

[1 2 3]
(3,)
int32
1
3
4
-----------
1
[10  2  3]
[20  0  6]


In [4]:
l = [1,2,3]
a = np.array([1,2,3])
print(a)
print(l)

l.append(4)
print(l)
a = a + np.array([4])
print(a)


# l = l*2
# print(l)
# a = a * 2
# print(a)

a = np.array([1,2,3])
a= np.sqrt(a)
print(a)

a = np.array([1,2,3])
a = np.log(a)
print(a)


#  dot product
l1 = [1,2,3]
l2 = [4,5,6]

c = np.array([1,2,3])

dot = 0
for i in range(len(l1)):
    dot += l1[i] * l2[i]
    
print(dot)

# using numpy
a1 = np.array(l1)
a2 = np.array(l2)

dot = np.dot(a1,a2)
print(dot)


sum1 = a1 * a2
dot = np.sum(sum1)
print(dot)


dot = a1 @ a2
print(dot)



[1 2 3]
[1, 2, 3]
[1, 2, 3, 4]
[5 6 7]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
32
32
32
32


In [5]:
# Multi dimentional arrays

a = np.array([[1,2],[3,4]])
print(a)
print(a.shape)

print(a[0][0])
print(a[0,0])
print(a[:,0]) # [1, , ] [3, , ]
print(a[0,:]) # [1, 2, 22]
print("Transpose")  
print(a.T) 
print(np.linalg.inv(a)) 

c = np.diag(a)
print(np.diag(c))


a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

b = a[0,1]
b = a[0,:]
print(b)
b = a[0,1:3]
print(b)
b = a[-1,-1]
print(b)








[[1 2]
 [3 4]]
(2, 2)
1
1
[1 3]
[1 2]
Transpose
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 0]
 [0 4]]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
[2 3]
8


In [6]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

bool_idx = a > 2
print(bool_idx)
print(a[bool_idx])
print(a[a > 2])


b = np.where(a>2, a, -1)
print(b)



[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [9]:
a = np.array([10,19,30,41,51,11,61])
print(a)
b = [1,3,5]
print(a[b])

[10 19 30 41 51 11 61]
[19 41 11]


In [15]:
a = np.array([10,19,30,41,50,11,61])
print(a)
even = np.argwhere(a%2==0).flatten()
print(a[even])

[10 19 30 41 50 11 61]
[10 30 50]


In [25]:
a = np.arange(1, 7)
print(a)
print(a.shape)
b = a.reshape((2, 3))
print(b.shape)
b = a[np.newaxis, :]
print(b)
b = a[:, np.newaxis]
print(b)

[1 2 3 4 5 6]
(6,)
(2, 3)
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [26]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]
