In [8]:
# Exercise:
# 1. Inventory Management (Retail): Write a program to categorize inventory based on stock quantity:
# Stock > 50: "In Stock"
# Stock > 10 and <= 50: "Low Stock"
# Stock <= 10: "Out of Stock"

print("Enter stock QTY: ")
stock = input()
print(stock)
stock = int(stock)

if stock > 50: print("In Stock")
elif stock > 10 and stock <= 50: print("Low Stock")
elif stock <= 10: print("Out of Stock")

Enter stock QTY: 
52
In Stock


In [9]:
# 2. Loan Approval (Banking): Create a program to decide if a customer’s loan should be approved based on:
# Credit score >= 750: "Loan Approved"
# Credit score between 600 and 749: "Loan Under Review"
# Credit score < 600: "Loan Denied"

print("Enter Your Credit Score: ")
score = int(input())
print(score)

if score >= 750: print("Loan Approved")
elif score >= 600 and score <= 749: print("Loan Under Review")
elif score < 600: print("Loan Denied")
 

Enter Your Credit Score: 
750
Loan Approved


In [12]:
# Salary Tax Bracket (Finance): Determine the tax bracket for an employee based on their salary:
# Salary > 1,00,000: 30%
# Salary between 50,000 and 1,00,000: 20%
# Salary < 50,000: 10%

print("Enter Your Salary: ")
salary = int(input())
print(salary)

if salary >= 100000: print("Your Tax Bracket is 30%")
elif salary >= 50000 and salary <= 100000: print("Your Tax Bracket is 20%")
elif salary < 50000: print("Your Tax Bracket is 10%")

Enter Your Salary: 
30000
Your Tax Bracket is 10%


In [2]:
import numpy as np

# Numpy is the backbone of ML
# Numpy implementations are in c language

In [2]:
print(np.__version__)

1.26.1


In [9]:
# Create an array
# Syntax np.array(data, dtype)
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# Clip function
# Syntax np.clip(array, min, max)
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.clip(arr, 2, 4))

# Functions
# 1. np.mean()
print(np.mean(arr))
# 2. np.median()
print(np.median(arr))
# 3. np.std()
print(np.std(arr))
# 4. np.var()
print(np.var(arr))


[1 2 3 4 5]
[2 2 3 4 4]
3.0
3.0
1.4142135623730951
2.0


In [12]:
import numpy as np
x = np.random.rand(5,5)
print(x)
#

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]]


In [1]:
import pandas